import './icons/storybook.js';
import './menu.button.js';
import './menu.link.js';
import './split-button.js';
import './split-button.primary-button.js';
import './split-button.primary-link.js';
import './split-button.secondary-button.js';
import type { Meta, StoryObj } from '@storybook/web-components';
declare const meta: Meta;
export default meta;
export declare const SplitButton: StoryObj;
export declare const WithIcon: StoryObj;
export declare const WithPrimaryLink: StoryObj;
