#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# It would be nice to simply run `NODE_ENV=production pnpm start` instead of
# individual scripts. But it would run `start:production:ts-morph`, which will
# fail, preventing push, whenever the developer has unstaged changes.
pnpm start:production:esbuild
pnpm start:production:storybook
pnpm start:production:typescript

NODE_ENV=production pnpm test
NODE_ENV=production pnpm typecheck
