#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# TODO: Say why not pnpm test, running everything. ts-moprh. no way to tell locally if uncommited changes are JSDOC changes.
pnpm start:production:esbuild
pnpm start:production:storybook
pnpm start:production:typescript
NODE_ENV=production pnpm test
NODE_ENV=production pnpm typecheck
