name: On Merge Branch "changeset-release/main"

on:
  pull_request:
    types: [closed]

env:
  CI: true

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install_dependencies:
    name: Install
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm

  build:
    name: Build
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - run: pnpm start
        env:
          NODE_ENV: production
      - uses: actions/upload-artifact@v4
        with:
          path: dist/storybook

  release:
    name: Release
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - install_dependencies

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - run: pnpm start
        env:
          NODE_ENV: production
      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
      - build
      - release
    steps:
      - uses: actions/download-artifact@v4
      - name: Configure AWS CLI
        env:
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}

        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
        run: |
          aws configure set region auto
          aws configure set output json
          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
      - name: Deploy
        run: aws s3 sync ./artifact s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/ --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
