name: On Push Branch "Main"

on:
  push:
    branches:
      - main

env:
  CI: true

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install_dependencies:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm

  release:
    name: Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - install_dependencies

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'Release Preview'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - run: NODE_ENV=production pnpm start
        env:
          BASE_URL: ${{ github.head_ref }}
      - uses: actions/upload-artifact@v4
        with:
          path: packages/components/dist/storybook

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
      - build
    steps:
      - uses: actions/download-artifact@v4
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS CLI
        env:
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}

        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
        run: |
          aws configure set region auto
          aws configure set output json
          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
      - name: Deploy
        run: aws s3 sync ./artifact s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }} --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
