name: On Pull Request Closed

on:
  pull_request:
    types: [closed]

jobs:
  remove_cloudflare_artifacts:
    name: Remove Cloudflare Artifacts
    # Ubuntu instead of MacOS because the performance difference is
    # negligible and Ubuntu includes the AWS CLI.
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/aws-cli
      - name: Remove Cloudflare artifacts
        run: aws s3 rm s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }} --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }} --recursive
