name: On Pull Request Closed

on:
  pull_request:
    types: [closed]

permissions: {}

defaults:
  run:
    shell: bash -eu -o pipefail {0}

jobs:
  remove-cloudflare-artifacts:
    name: Remove Cloudflare artifacts
    # Ubuntu instead of MacOS because the performance difference is
    # negligible and Ubuntu includes the AWS CLI.
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        env:
          CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
        # https://developers.cloudflare.com/r2/examples/aws/aws-cli
        run: |
          aws configure set region auto
          aws configure set output json
          aws configure set aws_access_key_id $CLOUDFLARE_R2_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $CLOUDFLARE_R2_SECRET_ACCESS_KEY
      - name: Remove artifacts
        run: |
          BRANCH="${{ github.head_ref }}"

          if [[ ! $BRANCH =~ ^[-a-zA-Z0-9_\/\.]+$ ]]; then
            echo "Invalid branch name"
            exit 1
          fi

          aws s3 rm s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/${{ github.head_ref }} --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }} --recursive
