name: On Push Branch "main"

on:
  push:
    branches:
      - main

env:
  CI: true

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install_dependencies:
    name: Install
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm

  release_preview:
    name: Release Preview
    timeout-minutes: 5
    runs-on: macos-latest
    needs:
      - install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          title: Release Preview
          commit: Version package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: macos-latest
    needs:
      - install_dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm
      - run: pnpm start
        env:
          BASE_URL: main
          NODE_ENV: production
      - uses: actions/upload-artifact@v4
        with:
          name: storybook
          path: dist/storybook

  deploy:
    name: Deploy
    # Ubuntu instead of MacOS because the performance difference is
    # negligible and Ubuntu includes the AWS CLI.
    runs-on: ubuntu-latest
    needs:
      - install_dependencies
      - build
    steps:
      # TODO: say why
      - uses: ./.github/workflows/update-snapshots.yml
      - uses: actions/download-artifact@v4
      - uses: ./.github/actions/aws-cli
      - name: Deploy
        run: aws s3 sync ./storybook s3://${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/main --endpoint-url ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
